//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wr_anit_cushman_one.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rscIdioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rscIdioma() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wr_anit_cushman_one.Resources.rscIdioma", typeof(rscIdioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrador.
        /// </summary>
        public static string Administrador {
            get {
                return ResourceManager.GetString("Administrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agua Potable.
        /// </summary>
        public static string Agua {
            get {
                return ResourceManager.GetString("Agua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altura libre.
        /// </summary>
        public static string AlturaLibreF {
            get {
                return ResourceManager.GetString("AlturaLibreF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altura libre.
        /// </summary>
        public static string AlturaLibreM {
            get {
                return ResourceManager.GetString("AlturaLibreM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año construcción.
        /// </summary>
        public static string AniosConstruccion {
            get {
                return ResourceManager.GetString("AniosConstruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        public static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido administrador.
        /// </summary>
        public static string ApellidoAdministrado {
            get {
                return ResourceManager.GetString("ApellidoAdministrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido broker.
        /// </summary>
        public static string ApellidoCorredor {
            get {
                return ResourceManager.GetString("ApellidoCorredor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido propietario.
        /// </summary>
        public static string ApellidoPropietario {
            get {
                return ResourceManager.GetString("ApellidoPropietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivos.
        /// </summary>
        public static string Archivos {
            get {
                return ResourceManager.GetString("Archivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area oficina.
        /// </summary>
        public static string AreaOficina {
            get {
                return ResourceManager.GetString("AreaOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cajones estacionamientos.
        /// </summary>
        public static string CajonesEstacionamiento {
            get {
                return ResourceManager.GetString("CajonesEstacionamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calle.
        /// </summary>
        public static string Calle {
            get {
                return ResourceManager.GetString("Calle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capacidad de carga piso.
        /// </summary>
        public static string Carga {
            get {
                return ResourceManager.GetString("Carga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cobertura máxima permitida.
        /// </summary>
        public static string CoberturaMaxima {
            get {
                return ResourceManager.GetString("CoberturaMaxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colonia.
        /// </summary>
        public static string Colonia {
            get {
                return ResourceManager.GetString("Colonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios.
        /// </summary>
        public static string comentarios {
            get {
                return ResourceManager.GetString("comentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Condiciones arrendamiento.
        /// </summary>
        public static string CondicionesArrendamiento {
            get {
                return ResourceManager.GetString("CondicionesArrendamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Corredor.
        /// </summary>
        public static string Corredor {
            get {
                return ResourceManager.GetString("Corredor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Broker.
        /// </summary>
        public static string CorredorIndustrial {
            get {
                return ResourceManager.GetString("CorredorIndustrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código postal.
        /// </summary>
        public static string CP {
            get {
                return ResourceManager.GetString("CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción área oficina.
        /// </summary>
        public static string DescripcionAreaOf {
            get {
                return ResourceManager.GetString("DescripcionAreaOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion cajones estacionamientos.
        /// </summary>
        public static string DescripcionCajonesEstac {
            get {
                return ResourceManager.GetString("DescripcionCajonesEstac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción carga.
        /// </summary>
        public static string DescripcionCarga {
            get {
                return ResourceManager.GetString("DescripcionCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción condiciones arrendamiento.
        /// </summary>
        public static string DescripcionCondiciones {
            get {
                return ResourceManager.GetString("DescripcionCondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion tipo gas.
        /// </summary>
        public static string DescripcionGas {
            get {
                return ResourceManager.GetString("DescripcionGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema de Ventilación.
        /// </summary>
        public static string DescripcionHVAC {
            get {
                return ResourceManager.GetString("DescripcionHVAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción iluminación.
        /// </summary>
        public static string DescripcionIluminacion {
            get {
                return ResourceManager.GetString("DescripcionIluminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion lampara.
        /// </summary>
        public static string DescripcionLampara {
            get {
                return ResourceManager.GetString("DescripcionLampara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción sistemas contra incendios.
        /// </summary>
        public static string DescripcionSistemaIncendio {
            get {
                return ResourceManager.GetString("DescripcionSistemaIncendio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo construcción.
        /// </summary>
        public static string DescripcionTipoConstruccion {
            get {
                return ResourceManager.GetString("DescripcionTipoConstruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponibilidad.
        /// </summary>
        public static string DisponibilidadTotalF {
            get {
                return ResourceManager.GetString("DisponibilidadTotalF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponibilidad total.
        /// </summary>
        public static string DisponibilidadTotalM {
            get {
                return ResourceManager.GetString("DisponibilidadTotalM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponible a partir de.
        /// </summary>
        public static string DisponibleApartir {
            get {
                return ResourceManager.GetString("DisponibleApartir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Energía eléctrica:.
        /// </summary>
        public static string EnergiaElectrica {
            get {
                return ResourceManager.GetString("EnergiaElectrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espesor de piso.
        /// </summary>
        public static string EspesorPiso {
            get {
                return ResourceManager.GetString("EspesorPiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espuela de ferrocarril.
        /// </summary>
        public static string Espuela {
            get {
                return ResourceManager.GetString("Espuela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus de entrega.
        /// </summary>
        public static string EstatusEntrega {
            get {
                return ResourceManager.GetString("EstatusEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gas natural.
        /// </summary>
        public static string GasNatural {
            get {
                return ResourceManager.GetString("GasNatural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HVAC.
        /// </summary>
        public static string HVAC {
            get {
                return ResourceManager.GetString("HVAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iluminación natural.
        /// </summary>
        public static string Iluminacion {
            get {
                return ResourceManager.GetString("Iluminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lámpara.
        /// </summary>
        public static string Lampara {
            get {
                return ResourceManager.GetString("Lampara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimiento areas comunes.
        /// </summary>
        public static string MantenimientoAreas {
            get {
                return ResourceManager.GetString("MantenimientoAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mapas.
        /// </summary>
        public static string Mapa {
            get {
                return ResourceManager.GetString("Mapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Máximo.
        /// </summary>
        public static string MaximoDisponible {
            get {
                return ResourceManager.GetString("MaximoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mercado.
        /// </summary>
        public static string Mercado {
            get {
                return ResourceManager.GetString("Mercado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mínimo.
        /// </summary>
        public static string MinimoDisponible {
            get {
                return ResourceManager.GetString("MinimoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mínimo divisible.
        /// </summary>
        public static string MinimoDivisibleF {
            get {
                return ResourceManager.GetString("MinimoDivisibleF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mínimo divisible.
        /// </summary>
        public static string MinimoDivisibleM {
            get {
                return ResourceManager.GetString("MinimoDivisibleM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio.
        /// </summary>
        public static string Municipio {
            get {
                return ResourceManager.GetString("Municipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Naves industriales.
        /// </summary>
        public static string NavesTitulo {
            get {
                return ResourceManager.GetString("NavesTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrada a Nivel de Piso.
        /// </summary>
        public static string NivelPisoNave {
            get {
                return ResourceManager.GetString("NivelPisoNave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. cajones trailer.
        /// </summary>
        public static string NoCajonesTrailer {
            get {
                return ResourceManager.GetString("NoCajonesTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre administrador.
        /// </summary>
        public static string NombreAdministrado {
            get {
                return ResourceManager.GetString("NombreAdministrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre comercial.
        /// </summary>
        public static string NombreComercial {
            get {
                return ResourceManager.GetString("NombreComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre broker.
        /// </summary>
        public static string NombreCorredor {
            get {
                return ResourceManager.GetString("NombreCorredor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre empresa.
        /// </summary>
        public static string NombreEmpresa {
            get {
                return ResourceManager.GetString("NombreEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre nave.
        /// </summary>
        public static string NombreNave {
            get {
                return ResourceManager.GetString("NombreNave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre parque.
        /// </summary>
        public static string NombreParque {
            get {
                return ResourceManager.GetString("NombreParque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre propietario.
        /// </summary>
        public static string NombrePropietario {
            get {
                return ResourceManager.GetString("NombrePropietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocupado hasta.
        /// </summary>
        public static string OcupadoHasta {
            get {
                return ResourceManager.GetString("OcupadoHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parque industrial.
        /// </summary>
        public static string ParqueIndustrial {
            get {
                return ResourceManager.GetString("ParqueIndustrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        public static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio de renta M2/mes.
        /// </summary>
        public static string PrecioRenta {
            get {
                return ResourceManager.GetString("PrecioRenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio total.
        /// </summary>
        public static string PrecioTotal {
            get {
                return ResourceManager.GetString("PrecioTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio de venta M2.
        /// </summary>
        public static string PrecioVenta {
            get {
                return ResourceManager.GetString("PrecioVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principal.
        /// </summary>
        public static string Principal {
            get {
                return ResourceManager.GetString("Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propietario.
        /// </summary>
        public static string Propietario {
            get {
                return ResourceManager.GetString("Propietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puertas andén.
        /// </summary>
        public static string PuertaAnden {
            get {
                return ResourceManager.GetString("PuertaAnden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puesto.
        /// </summary>
        public static string Puesto {
            get {
                return ResourceManager.GetString("Puesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rampa.
        /// </summary>
        public static string Rampa {
            get {
                return ResourceManager.GetString("Rampa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Cliente.
        /// </summary>
        public static string RepNombreCliente {
            get {
                return ResourceManager.GetString("RepNombreCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios.
        /// </summary>
        public static string Servicio {
            get {
                return ResourceManager.GetString("Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefonía.
        /// </summary>
        public static string ServicioTelecomunicaciones {
            get {
                return ResourceManager.GetString("ServicioTelecomunicaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistemas contra incendios.
        /// </summary>
        public static string SistemasIncendio {
            get {
                return ResourceManager.GetString("SistemasIncendio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Superficie nave.
        /// </summary>
        public static string SuperficieNaveF {
            get {
                return ResourceManager.GetString("SuperficieNaveF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Superficie nave.
        /// </summary>
        public static string SuperficieNaveM {
            get {
                return ResourceManager.GetString("SuperficieNaveM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Superficie terreno.
        /// </summary>
        public static string SuperficieTerrenoF {
            get {
                return ResourceManager.GetString("SuperficieTerrenoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Superficie terreno.
        /// </summary>
        public static string SuperficieTerrenoM {
            get {
                return ResourceManager.GetString("SuperficieTerrenoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Superficie Terreno.
        /// </summary>
        public static string SuperficieTotalBodegaF {
            get {
                return ResourceManager.GetString("SuperficieTotalBodegaF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Superficie Terreno.
        /// </summary>
        public static string SuperficieTotalBodegaM {
            get {
                return ResourceManager.GetString("SuperficieTotalBodegaM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño max lote.
        /// </summary>
        public static string TamanioMaximoF {
            get {
                return ResourceManager.GetString("TamanioMaximoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño máximo de lote .
        /// </summary>
        public static string TamanioMaximoM {
            get {
                return ResourceManager.GetString("TamanioMaximoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tam mín del lote.
        /// </summary>
        public static string TamanioMinimoF {
            get {
                return ResourceManager.GetString("TamanioMinimoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño mínimo de lote.
        /// </summary>
        public static string TamanioMinimoM {
            get {
                return ResourceManager.GetString("TamanioMinimoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño del parque.
        /// </summary>
        public static string TamanioParque {
            get {
                return ResourceManager.GetString("TamanioParque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Techumbre de nave.
        /// </summary>
        public static string TechumbreNave {
            get {
                return ResourceManager.GetString("TechumbreNave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terreno.
        /// </summary>
        public static string terrenoTitulo {
            get {
                return ResourceManager.GetString("terrenoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo construccion.
        /// </summary>
        public static string TipoConstruccion {
            get {
                return ResourceManager.GetString("TipoConstruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo moneda.
        /// </summary>
        public static string TipoMoneda {
            get {
                return ResourceManager.GetString("TipoMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo moneda reporte.
        /// </summary>
        public static string TipoMonedaReport {
            get {
                return ResourceManager.GetString("TipoMonedaReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edificio/Terreno.
        /// </summary>
        public static string TipoReporte {
            get {
                return ResourceManager.GetString("TipoReporte", resourceCulture);
            }
        }
    }
}
